version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.18
  cpp-executor:
    docker:
      - image: cimg/base:stable
  rust-executor:
    docker:
      - image: cimg/rust:1.65

jobs:
  cpp-build:
    executor: cpp-executor
    steps:
      - checkout
      - run:
          name: Setup cmake and build artifacts
          command: |
            cd lib/cpp/
            mkdir build
            cd build
            cmake ..
            cmake --build .
      - persist_to_workspace:
          root: .
          paths: [lib/cpp/build]

  cpp-test:
    executor: cpp-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: |
            cd lib/cpp/build
            tests/zddm_test --gtest_output="xml:test-results.xml"
      - store_test_results:
          path: lib/cpp/build

  go-test:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            cd lib/go
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            gotestsum --junitfile test-results.xml -- $PACKAGE_NAMES
      - store_test_results:
          path: lib/go 

  rust-test:
    executor: rust-executor
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            cd lib/rust
            cargo test

workflows:
  version: 2
  rust-test:
    jobs:
      - rust-test
  go-test:
    jobs:
      - go-test
  cpp-build-and-test:
    jobs:
      - cpp-build
      - cpp-test:
          requires:
            - cpp-build


